### ISSUE TITLE
Template not being rendered inside a block in EPi10

### ISSUE THREAD

**Issue by cbermar** [joseftw/JOS.PropertyKeyValueList#3]
First, nice property. I am creating a EPi10 site and pulled it down, but noticed that it did not render the template correctly in the creating view of a block. So after some research it seems EPi is triggering a method inside the widget with null values, so things break.

I created a pull request with the fix for this.

Thanks for a nice blog post and a nice a property for EPi!

**Comment by joseftw** [comment]
Hey! I will have a look at it as soon as I can, probably tonight!
The javascript portion of the property is kinda...not good, so I will have a look and see if I can refactor it a bit.

**Comment by joseftw** [comment]
I've tried to reproduce this but I can't? I've tested on the latest version of the Alloy site, could you please provide me with more details of how to reproduce this?

**Comment by cbermar** [comment]
Strange. I debugged the script (KeyValueList.js) and noticed _setValueAttr got called with null parameters, which caused the init-screen to be rendered without controls. After adding the null-check, it ran fine.

![empty_view_on_create](https://cloud.githubusercontent.com/assets/152401/26052462/e38c126e-3965-11e7-97bc-3875d29c7209.png)
